site_name: Motofumi Fushimi
site_url: https://motofumi-fushimi.github.io
docs_dir: docs

theme:
  name: material
  language: ja
  features:
    - navigation.tabs
    - navigation.top
  palette:
    - scheme: default
  icon:
    logo: fontawesome/solid/graduation-cap
  favicon: Images/favicon.ico

copyright: © 2026 Motofumi Fushimi. All Rights Reserved.

extra:
  generator: false

extra_css:
  - website.css
  - https://unpkg.com/katex@0/dist/katex.min.css

extra_javascript:
  - Macros/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

plugins:
  - search
  - exclude:
      glob:
        - ".git/**/*"
        - ".github/**/*"
        - ".devcontainer/**/*"
        - ".vscode/**/*"
        - ".gitignore"
        - ".gitattributes"
        - "mkdocs.yml"
        - "readme.md"

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
